TEXTS = {
    "en": {
        "welcome": "Hello, {name}!\n\nSend me a link to a video start downloaded.\n\n(Language auto-detected. Settings: /language)",
        "language_selected": "Language set to English! Send me a link.",
        "processing": "Processing... Please wait...",
        "video_too_large": "The video is too large ({size:.2f} MB). Limit is 4GB.",
        "download_failed": "Failed to download video.",
        "file_not_found": "File not found.",
        "error": "An error occurred.",
        "choose_language": "Choose your language:",
        "btn_name": "🇺🇸 English",
        "download_progress": "📥 DL: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Live streams not supported.",
        "error_age": "Age restricted content.",
        "select_format": "🎬 {title}\n⏱ Duration: {duration}\n\n📝 Choose quality:",
        "btn_video": "📹 Video",
        "btn_audio": "🎵 Audio (MP3)",
        "btn_low": "📱 Low (360p)",
        "btn_med": "💿 Medium (720p)",
        "btn_high": "💎 High (1080p)",
        "analyzing": "⏳ Analyzing video...",
    },
    "ru": {
        "welcome": "Привет, {name}!\n\nОтправь ссылку для скачивания.\n\n(Язык авто-определен. Настройки: /language)",
        "language_selected": "Язык: Русский. Отправь ссылку.",
        "processing": "Обработка...",
        "video_too_large": "Видео слишком большое ({size:.2f} MB). Лимит 4ГБ.",
        "download_failed": "Ошибка скачивания.",
        "file_not_found": "Файл не найден.",
        "error": "Произошла ошибка.",
        "choose_language": "Выберите язык:",
        "btn_name": "🇷🇺 Русский",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Стримы не поддерживаются.",
        "error_age": "Возрастное ограничение.",
        "select_format": "🎬 {title}\n⏱ Длительность: {duration}\n\n📝 Выберите качество:",
        "btn_video": "📹 Видео",
        "btn_audio": "🎵 Аудио (MP3)",
        "btn_low": "📱 Низкое (360p)",
        "btn_med": "💿 Среднее (720p)",
        "btn_high": "💎 Высокое (1080p)",
        "analyzing": "⏳ Анализ видео...",
    },
    "uk": {
        "welcome": "Привіт, {name}!\n\nНадішли посилання для завантаження.\n\n(Мову визначено. Налаштування: /language)",
        "language_selected": "Мова: Українська. Надішли посилання.",
        "processing": "Обробка...",
        "video_too_large": "Відео завелике ({size:.2f} MB). Ліміт 4ГБ.",
        "download_failed": "Помилка завантаження.",
        "file_not_found": "Файл не знайдено.",
        "error": "Сталася помилка.",
        "choose_language": "Оберіть мову:",
        "btn_name": "🇺🇦 Українська",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Стріми не підтримуються.",
        "error_age": "Вікові обмеження.",
    },
    "kk": {
        "welcome": "Сәлем, {name}!\n\nЖүктеу үшін сілтеме жіберіңіз.\n\n(Тіл анықталды. Баптаулар: /language)",
        "language_selected": "Тіл: Қазақша. Сілтеме жіберіңіз.",
        "processing": "Өңделуде...",
        "video_too_large": "Видео тым үлкен ({size:.2f} MB). Шектеу 4ГБ.",
        "download_failed": "Жүктеу қатесі.",
        "file_not_found": "Файл табылмады.",
        "error": "Қате орын алды.",
        "choose_language": "Тілді таңдаңыз:",
        "btn_name": "🇰🇿 Қазақша",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Тікелей эфир жүктелмейді.",
        "error_age": "Жас шектеуі.",
    },
    "de": {
        "welcome": "Hallo, {name}!\n\nSenden Sie mir einen Link zum Herunterladen.\n\n(Sprache erkannt. Einstellungen: /language)",
        "language_selected": "Sprache: Deutsch. Link senden.",
        "processing": "Verarbeitung...",
        "video_too_large": "Video zu groß ({size:.2f} MB). Limit 4GB.",
        "download_failed": "Download fehlgeschlagen.",
        "file_not_found": "Datei nicht gefunden.",
        "error": "Ein Fehler ist aufgetreten.",
        "choose_language": "Sprache wählen:",
        "btn_name": "🇩🇪 Deutsch",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Live-Streams nicht unterstützt.",
        "error_age": "Altersbeschränkung.",
    },
    "es": {
        "welcome": "¡Hola, {name}!\n\nEnvíame un enlace para descargar.\n\n(Idioma detectado. Ajustes: /language)",
        "language_selected": "Idioma: Español. Envía un enlace.",
        "processing": "Procesando...",
        "video_too_large": "Video demasiado grande ({size:.2f} MB). Límite 4GB.",
        "download_failed": "Error de descarga.",
        "file_not_found": "Archivo no encontrado.",
        "error": "Ocurrió un error.",
        "choose_language": "Elige tu idioma:",
        "btn_name": "🇪🇸 Español",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Directos no soportados.",
        "error_age": "Restricción de edad.",
    },
    "pt": {
        "welcome": "Olá, {name}!\n\nEnvie-me um link para baixar.\n\n(idioma detectado. Configurações: /language)",
        "language_selected": "Idioma: Português. Envie um link.",
        "processing": "Processando...",
        "video_too_large": "Vídeo muito grande ({size:.2f} MB). Limite 4GB.",
        "download_failed": "Falha no download.",
        "file_not_found": "Arquivo não encontrado.",
        "error": "Ocorreu um erro.",
        "choose_language": "Escolha seu idioma:",
        "btn_name": "🇵🇹 Português",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Lives não suportadas.",
        "error_age": "Restrição de idade.",
    },
    "fr": {
        "welcome": "Bonjour, {name}!\n\nEnvoyez-moi un lien pour télécharger.\n\n(Langue détectée. Paramètres: /language)",
        "language_selected": "Langue: Français. Envoyez un lien.",
        "processing": "Traitement...",
        "video_too_large": "Vidéo trop grande ({size:.2f} MB). Limite 4GB.",
        "download_failed": "Échec du téléchargement.",
        "file_not_found": "Fichier introuvable.",
        "error": "Une erreur est survenue.",
        "choose_language": "Choisissez votre langue:",
        "btn_name": "🇫🇷 Français",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Directs non supportés.",
        "error_age": "Limite d'âge.",
    },
    "it": {
        "welcome": "Ciao, {name}!\n\nInviami un link per scaricare.\n\n(Lingua rilevata. Impostazioni: /language)",
        "language_selected": "Lingua: Italiano. Invia un link.",
        "processing": "Elaborazione...",
        "video_too_large": "Video troppo grande ({size:.2f} MB). Limite 4GB.",
        "download_failed": "Scaricamento fallito.",
        "file_not_found": "File non trovato.",
        "error": "Si è verificato un errore.",
        "choose_language": "Scegli la lingua:",
        "btn_name": "🇮🇹 Italiano",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Live non supportate.",
        "error_age": "Restrizione di età.",
    },
    "ar": {
        "welcome": "مرحباً {name}!\n\nأرسل لي رابطاً للتحميل.\n\n(تم اكتشاف اللغة. الإعدادات: /language)",
        "language_selected": "اللغة: العربية. أرسل رابطاً.",
        "processing": "جارٍ المعالجة...",
        "video_too_large": "الفيديو كبير جداً ({size:.2f} MB). الحد 4 جيجابايت.",
        "download_failed": "فشل التحميل.",
        "file_not_found": "الملف غير موجود.",
        "error": "حدث خطأ.",
        "choose_language": "اختر لغتك:",
        "btn_name": "🇸🇦 العربية",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "البث المباشر غير مدعوم.",
        "error_age": "محتوى مقيد بالعمر.",
    },
    "fa": {
        "welcome": "سلام {name}!\n\nیک لینک برای دانلود ارسال کنید.\n\n(زبان شناسایی شد. تنظیمات: /language)",
        "language_selected": "زبان: فارسی. لینک بفرستید.",
        "processing": "در حال پردازش...",
        "video_too_large": "ویدیو خیلی حجیم است ({size:.2f} MB). محدودیت 4 گیگابایت.",
        "download_failed": "دانلود ناموفق بود.",
        "file_not_found": "فایل یافت نشد.",
        "error": "خطایی رخ داد.",
        "choose_language": "زبان خود را انتخاب کنید:",
        "btn_name": "🇮🇷 فارسی",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "لایو پشتیبانی نمی‌شود.",
        "error_age": "محدودیت سنی.",
    },
    "tr": {
        "welcome": "Merhaba, {name}!\n\nİndirmek için bir bağlantı gönderin.\n\n(Dil algılandı. Ayarlar: /language)",
        "language_selected": "Dil: Türkçe. Bağlantı gönder.",
        "processing": "İşleniyor...",
        "video_too_large": "Video çok büyük ({size:.2f} MB). Sınır 4GB.",
        "download_failed": "İndirme başarısız.",
        "file_not_found": "Dosya bulunamadı.",
        "error": "Bir hata oluştu.",
        "choose_language": "Dilinizi seçin:",
        "btn_name": "🇹🇷 Türkçe",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Canlı yayınlar desteklenmiyor.",
        "error_age": "Yaş kısıtlaması.",
    },
    "uz": {
        "welcome": "Salom, {name}!\n\nYuklash uchun havola yuboring.\n\n(Til aniqlandi. Sozlamalar: /language)",
        "language_selected": "Til: O'zbek. Havola yuboring.",
        "processing": "Qayta ishlanmoqda...",
        "video_too_large": "Video juda katta ({size:.2f} MB). Cheklov 4GB.",
        "download_failed": "Yuklashda xatolik.",
        "file_not_found": "Fayl topilmadi.",
        "error": "Xatolik yuz berdi.",
        "choose_language": "Tilingizni tanlang:",
        "btn_name": "🇺🇿 O‘zbek",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Jonli efirlar qo'llab-quvvatlanmaydi.",
        "error_age": "Yosh cheklovi.",
    },
    "id": {
        "welcome": "Halo, {name}!\n\nKirimkan tautan untuk mengunduh.\n\n(Bahasa terdeteksi. Pengaturan: /language)",
        "language_selected": "Bahasa: Indonesia. Kirim tautan.",
        "processing": "Memproses...",
        "video_too_large": "Video terlalu besar ({size:.2f} MB). Batas 4GB.",
        "download_failed": "Gagal mengunduh.",
        "file_not_found": "Berkas tidak ditemukan.",
        "error": "Terjadi kesalahan.",
        "choose_language": "Pilih bahasa Anda:",
        "btn_name": "🇮🇩 Indonesia",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Siaran langsung tidak didukung.",
        "error_age": "Pembatasan usia.",
    },
    "hi": {
        "welcome": "नमस्ते, {name}!\n\nडाउनलोड करने के लिए लिंक भेजें.\n\n(भाषा का पता चला. सेटिंग्स: /language)",
        "language_selected": "भाषा: हिंदी. लिंक भेजें.",
        "processing": "प्रक्रिया जारी है...",
        "video_too_large": "वीडियो बहुत बड़ा है ({size:.2f} MB). सीमा 4GB.",
        "download_failed": "डाउनलोड विफल.",
        "file_not_found": "फ़ाइल नहीं मिली.",
        "error": "त्रुटि हुई.",
        "choose_language": "अपनी भाषा चुनें:",
        "btn_name": "🇮🇳 हिन्दी",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "लाइव स्ट्रीम समर्थित नहीं हैं.",
        "error_age": "आयु प्रतिबंधित.",
    },
    "nl": {
        "welcome": "Hallo, {name}!\n\nStuur een link om te downloaden.\n\n(Taal gedetecteerd. Instellingen: /language)",
        "language_selected": "Taal: Nederlands. Stuur een link.",
        "processing": "Verwerken...",
        "video_too_large": "Video te groot ({size:.2f} MB). Limiet 4GB.",
        "download_failed": "Download mislukt.",
        "file_not_found": "Bestand niet gevonden.",
        "error": "Er is een fout opgetreden.",
        "choose_language": "Kies uw taal:",
        "btn_name": "🇳🇱 Nederlands",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Live streams niet ondersteund.",
        "error_age": "Leeftijdsbeperking.",
    },
    "pl": {
        "welcome": "Cześć, {name}!\n\nWyślij link do pobrania.\n\n(Język wykryty. Ustawienia: /language)",
        "language_selected": "Język: Polski. Wyślij link.",
        "processing": "Przetwarzanie...",
        "video_too_large": "Wideo zbyt duże ({size:.2f} MB). Limit 4GB.",
        "download_failed": "Pobieranie nie powiodło się.",
        "file_not_found": "Nie znaleziono pliku.",
        "error": "Wystąpił błąd.",
        "choose_language": "Wybierz język:",
        "btn_name": "🇵🇱 Polski",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Transmisje na żywo nieobsługiwane.",
        "error_age": "Ograniczenie wiekowe.",
    },
    "vi": {
        "welcome": "Xin chào, {name}!\n\nGửi liên kết để tải xuống.\n\n(Đã phát hiện ngôn ngữ. Cài đặt: /language)",
        "language_selected": "Ngôn ngữ: Tiếng Việt. Gửi liên kết.",
        "processing": "Đang xử lý...",
        "video_too_large": "Video quá lớn ({size:.2f} MB). Giới hạn 4GB.",
        "download_failed": "Tải xuống thất bại.",
        "file_not_found": "Không tìm thấy tệp.",
        "error": "Đã xảy ra lỗi.",
        "choose_language": "Chọn ngôn ngữ:",
        "btn_name": "🇻🇳 Tiếng Việt",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Livestream không được hỗ trợ.",
        "error_age": "Giới hạn độ tuổi.",
    },
    "zh": {
        "welcome": "你好, {name}!\n\n发送链接以开始下载。\n\n(已检测到语言。设置: /language)",
        "language_selected": "语言: 中文。发送链接。",
        "processing": "处理中...",
        "video_too_large": "视频太大 ({size:.2f} MB). 限制 4GB.",
        "download_failed": "下载失败。",
        "file_not_found": "未找到文件。",
        "error": "发生错误。",
        "choose_language": "选择语言:",
        "btn_name": "🇨🇳 中文",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "不支持直播。",
        "error_age": "年龄限制。",
    },
    "ms": {
        "welcome": "Helo, {name}!\n\nHantar pautan untuk muat turun.\n\n(Bahasa dikesan. Tetapan: /language)",
        "language_selected": "Bahasa: Melayu. Hantar pautan.",
        "processing": "Sedang diproses...",
        "video_too_large": "Video terlalu besar ({size:.2f} MB). Had 4GB.",
        "download_failed": "Gagal memuat turun.",
        "file_not_found": "Fail tidak ditemui.",
        "error": "Ralat berlaku.",
        "choose_language": "Pilih bahasa anda:",
        "btn_name": "🇲🇾 Melayu",
        "download_progress": "📥: {percent} | 💾 {total} | 🚀 {speed}",
        "error_live": "Siaran langsung tidak disokong.",
        "error_age": "Sekatan umur.",
    },
}